### ISSUE TITLE
cannot get to the provided URL to get device information

### ISSUE THREAD

**Issue by ufcfanatic** [marksull/err-backend-cisco-webex-teams#19]
Hey Mark I tried this URL you put in the code and it does not work - DEVICES_URL = 'https://wdm-a.wbx2.com/wdm/api/v1/devices
![Screenshot (8)](https://user-images.githubusercontent.com/5713659/59805023-f38e6c80-92a4-11e9-8a6d-74dd9cc16b67.png)
'

Is there an updated URL to use ?

**Comment by mh720** [comment]
That endpoint works for my errbot, it's an API endpoint and so requires authentication via webex API.

**Comment by marksull** [comment]
Yeah its not something you can just browse too. Check out _get_device_info() to see how that URL is used as part of an authenticated webex session.
