### ISSUE TITLE
Could not find a user using the email address {self.email}

### ISSUE THREAD

**Issue by ahusking** [marksull/err-backend-cisco-webex-teams#20]
Hi There,

Seem to be having the same issues as with #6, but i can confirm that i'm running python 3.6.5.

Any advice on where to look for the issue?

i'm seeing the following in the logs.

16:17:19 INFO     errbot.core_plugins.wsvie Checking TextModeCmds for webhooks
16:17:19 DEBUG    errbot.plugin_manager     Activate flow plugins ...
16:17:19 DEBUG    urllib3.connectionpool    https://api.ciscospark.com:443 "GET /v1/people?email=A HTTP/1.1" 400 144
16:17:19 ERROR    errbot.backends.base      Exception occurred in serve_once:

The email=A seems to change based on what email address i have in the BOT_ADMIN variable, but only ever returns the first letter.

TIA

**Comment by marksull** [comment]
Sounds like your BOT_ADMIN variable set incorrectly. Is it defined as a tuple? For example

BOT_ADMINS = ('youremail@domain.com', ) 

Note the trailing comma, if you don't include it this is a string, not a tuple, and errbot expects a tuple.
