### ISSUE TITLE
Proxy Support for WebexTeams Backend?

### ISSUE THREAD

**Issue by T3CHKOMMIE** [marksull/err-backend-cisco-webex-teams#22]
Hello, 

Ive been trying to get the backend to connect through a HTTP proxy. seems like Im hitting a limitation in websockets module that doesnt support proxy settings.

I was pointed to websocket-client module, but using that module seems to throw attribute errors __aexit__ in the async code for the websockets. looks like websocket-client connect function isnt a context manager?

not sure how to go about changing the backend to get it to pass through a proxy. Any ideas?

**Comment by mh720** [comment]
Hoping Mark that you might have some time to look into adding proxy support for this backend, glad to help test if you want to ping me on Webex Teams. @T3CHKOMMIE I think you might have implemented something like this: https://stackoverflow.com/questions/47225488/client-websocket-connect-through-proxy

Slack client uses AIOHttp, so not much help there without some refactoring, but for reference:

https://github.com/errbotio/errbot/commit/d0d71e991233ba7fd787420866c7e2afebba1274#diff-4d2174262014c51fc8b38e02b99962bd

https://pypi.org/project/slackclient/

https://pypi.org/project/aiohttp-proxy/

**Comment by marksull** [comment]
There are only two open issues on this repo. Check out the other open issue #18. 😜
