### ISSUE TITLE
Formatted UUIDs no longer supported

### ISSUE THREAD

**Issue by gachteme** [marksull/err-backend-cisco-webex-teams#32]
https://developer.webex.com/docs/api/changelog#2021-april April 27 warning

This breaks all functionality.

**Comment by marksull** [comment]
@gachteme that doesn't look good. I should probably pay closer attention to the release notes. All my bots are still running fine. Has this already impacted you or are you speculating that it will impact us in the near(ish) future?

**Comment by gachteme** [comment]
I have seen some instances where webex does return identifiers in the UUID format instead of the new ID format that is mentioned and had failures.

**Comment by marksull** [comment]
i would need more information, like a stack trace etc if you can capture/recreate an issue. I don't see anywhere in the code where we are specifically expecting a UUID other than we setup the websocket connection (but this is not an API generated ID). We are always loading the ids from the API response which as the change log documentation states "If you use the identifiers returned by the API endpoints in other developer.webex.com API endpoints your app requests can be routed correctly." The plugin also relies heavily on the ```webexteamssdk``` package and I had a quick scan of its codebase I didn't see any reliance on UUIDs.

**Comment by marksull** [comment]
@gachteme turns out this become an issue ;-). Version 1.10.0 released that should resolve these issues.
